import {recipes,recipeByName} from '../data/recipes';
import {packageLine} from '../data/packaging';
export const days=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag'];
export const defaultPlan={Maandag:['Mediterrane Couscous','Kip Curry Light'],Dinsdag:['Tonijn Pasta Light','Taco Bowl'],Woensdag:['Skyr Protein Bowl','Kip Teriyaki Bowl'],Donderdag:['Tonijn Pasta Light','Zalm met Broccoli'],Vrijdag:['Mediterrane Couscous','Uit eten / overslaan'],Zaterdag:['Uit eten / overslaan','Uit eten / overslaan'],Zondag:['Skyr Protein Bowl','Kip Teriyaki Bowl']};
export const defaultState={profile:{name:'Dominique',age:34,sex:'vrouw',height:172,startWeight:75,weight:75,goal:65,kcal:1600,protein:130,maintenance:2200,water:2.5},plan:defaultPlan,weights:[{date:new Date().toISOString().slice(0,10),weight:75}],checkedItems:{},pantry:{},foodLog:[],favorites:[]};
export function calculateShopping(plan,pantry={}){const totals={},cats={};let kcal=0,protein=0;const dayTotals={};days.forEach(day=>{let dayKcal=0,dayProtein=0;(plan[day]||[]).forEach(meal=>{const recipe=recipeByName[meal]||recipeByName['Uit eten / overslaan'];kcal+=recipe.kcal||0;protein+=recipe.protein||0;dayKcal+=recipe.kcal||0;dayProtein+=recipe.protein||0;(recipe.ingredients||[]).forEach(([name,amount,unit,cat])=>{const key=`${name}|${unit}`;totals[key]=(totals[key]||0)+amount;cats[name]=cat})});dayTotals[day]={kcal:dayKcal,protein:dayProtein}});const grouped={},adjustedTotals={};Object.entries(totals).forEach(([key,amount])=>{const [name,unit]=key.split('|');const inHouse=Number(pantry[key]||0);const needed=Math.max(0,amount-inHouse);adjustedTotals[key]=needed;const cat=cats[name]||'Overig';if(!grouped[cat])grouped[cat]=[];grouped[cat].push({key,name,amount,inHouse,needed,unit,line:needed===0?`${name}: genoeg in huis`:packageLine(name,needed,unit)})});const picnicText=Object.entries(adjustedTotals).filter(([,a])=>a>0).sort(([a],[b])=>a.localeCompare(b)).map(([key,amount])=>{const [name,unit]=key.split('|');return `${name} ${amount} ${unit}`}).join('\n');return{totals,adjustedTotals,grouped,picnicText,kcal,protein,dayTotals}}
export function trend(weights){if(!weights||weights.length<2)return null;const sorted=[...weights].reverse();const first=sorted[0],last=sorted[sorted.length-1];const daysBetween=Math.max(1,(new Date(last.date)-new Date(first.date))/(1000*60*60*24));return{weekly:((last.weight-first.weight)/daysBetween)*7}}
export function targetDate(weeks){if(!weeks)return '—';const d=new Date();d.setDate(d.getDate()+weeks*7);return d.toLocaleDateString('nl-NL',{day:'numeric',month:'long'})}
export const foodDb=[{keys:['skyr'],kcal:200,protein:30,carbs:12,fat:1},{keys:['muesli'],kcal:95,protein:3,carbs:17,fat:2},{keys:['banaan'],kcal:110,protein:1,carbs:27,fat:0},{keys:['kip'],kcal:250,protein:45,carbs:0,fat:6},{keys:['rijst'],kcal:180,protein:4,carbs:39,fat:1},{keys:['broccoli'],kcal:70,protein:5,carbs:8,fat:1},{keys:['tonijn'],kcal:130,protein:28,carbs:0,fat:1},{keys:['pasta'],kcal:230,protein:8,carbs:45,fat:2},{keys:['zalm'],kcal:300,protein:32,carbs:0,fat:18},{keys:['pizza'],kcal:850,protein:35,carbs:90,fat:35},{keys:['ei','eieren'],kcal:75,protein:6,carbs:1,fat:5},{keys:['shake','eiwitshake'],kcal:120,protein:24,carbs:3,fat:2}];
export function estimateFood(text){const lower=text.toLowerCase();let kcal=0,protein=0,carbs=0,fat=0;const matched=[];const explicitKcal=lower.match(/(\d{2,4})\s*(kcal|calorie|calorieen|calorieën)/);const explicitProtein=lower.match(/(\d{1,3})\s*(g\s*)?(eiwit|protein)/);foodDb.forEach(item=>{const key=item.keys.find(k=>lower.includes(k));if(!key)return;const grams=lower.match(new RegExp('(\\d+(?:[,.]\\d+)?)\\s*(g|gram)\\s*'+key));const amount=lower.match(new RegExp('(\\d+(?:[,.]\\d+)?)\\s*(x|keer|stuks?|glazen?|koppen?)?\\s*'+key));let mult=1;if(grams)mult=Number(grams[1].replace(',','.'))/100;else if(amount)mult=Number(amount[1].replace(',','.'))||1;kcal+=item.kcal*mult;protein+=item.protein*mult;carbs+=item.carbs*mult;fat+=item.fat*mult;matched.push(mult!==1?`${Math.round(mult*10)/10}× ${key}`:key)});if(explicitKcal)kcal=Number(explicitKcal[1]);if(explicitProtein)protein=Number(explicitProtein[1]);if(!kcal){kcal=500;protein=20;carbs=45;fat=18;matched.push('algemene maaltijd')}return{text,kcal:Math.round(kcal),protein:Math.round(protein),carbs:Math.round(carbs),fat:Math.round(fat),matched,date:new Date().toISOString().slice(0,10),time:new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'})}}
export function suggestRecipes(kcalLeft,proteinLeft,favorites=[]){const main=recipes.map(r=>{const score=Math.abs(kcalLeft-r.kcal)+Math.max(0,proteinLeft-r.protein)*8+(favorites.includes(r.id)?-80:0);return{...r,score}}).sort((a,b)=>a.score-b.score).slice(0,3);const snack=recipes.find(r=>r.type==='snack')||main[0];return{main,snack}}
export function coachAdvice(kcalLeft,proteinLeft,suggestions){if(kcalLeft<=0)return['Je zit qua kcal al op of boven je dagdoel. Houd de rest licht.','Morgen gewoon terug naar je normale plan; niet extreem compenseren.'];const first=suggestions?.main?.[0];if(first)return[`Beste match nu: ${first.name} (${first.kcal} kcal, ${first.protein} g eiwit).`,proteinLeft>first.protein?`Neem daarna eventueel ${suggestions.snack.name} om dichter bij je eiwitdoel te komen.`:'Daarmee zit je goed voor de rest van de dag.'];return[`Je hebt nog ${kcalLeft} kcal en ${proteinLeft} g eiwit over.`]}
